NAME = push_swap
CC = cc
FLAGS = -Wall -Wextra -Werror
OBJ = {Source:}
RM = rm -f
SOURCE = 

all: ${NAME}
${NAME}: 
clean:
${RM} ${OBJ}
.o:.c
${CC} {FLAGS} 
fclean: clean
${RM} ${NAME}
re: all
.PHONY: all clean fclean re